import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Analytics } from "@vercel/analytics/react"
import "./globals.css";

const outfit = Outfit({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "BetterDev - Senior Engineer at one click ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={outfit.className}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
